version: "3.8"

services:
  mariadb:
<<<<<<< HEAD
    image: mariadb:10.6
    container_name: mystudy-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: S6868645s
      MARIADB_DATABASE: mystudy-db
      MARIADB_USER: studyuser
      MARIADB_PASSWORD: S6868645s
=======
    image: mariadb:11
    container_name: studyplanner-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: studyplanner 
      MARIADB_USER: studyuser
      MARIADB_PASSWORD: studypass
>>>>>>> 60275efaa897e2ccda2fb5d032e748394b97ad35
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
<<<<<<< HEAD
  mariadb_data:
=======
  mariadb_data:
>>>>>>> 60275efaa897e2ccda2fb5d032e748394b97ad35
